<?php
/**
 * WebDavLogin
 *
 * PHP version 5
 *
 * @category Class
 * @package  Inwendo\WebDav\Common
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inwendo WebDav Service
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Inwendo\WebDav\Common\Model;

use \ArrayAccess;

/**
 * WebDavLogin Class Doc Comment
 *
 * @category    Class */
 // @description WebDavLogin
/** 
 * @package     Inwendo\WebDav\Common
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WebDavLogin implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'WebDavLogin';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id' => 'int',
        'webdav_username' => 'string',
        'webdav_password' => 'string',
        'webdav_url' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id' => 'id',
        'webdav_username' => 'webdavUsername',
        'webdav_password' => 'webdavPassword',
        'webdav_url' => 'webdavUrl'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id' => 'setId',
        'webdav_username' => 'setWebdavUsername',
        'webdav_password' => 'setWebdavPassword',
        'webdav_url' => 'setWebdavUrl'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id' => 'getId',
        'webdav_username' => 'getWebdavUsername',
        'webdav_password' => 'getWebdavPassword',
        'webdav_url' => 'getWebdavUrl'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['webdav_username'] = isset($data['webdav_username']) ? $data['webdav_username'] : null;
        $this->container['webdav_password'] = isset($data['webdav_password']) ? $data['webdav_password'] : null;
        $this->container['webdav_url'] = isset($data['webdav_url']) ? $data['webdav_url'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets webdav_username
     * @return string
     */
    public function getWebdavUsername()
    {
        return $this->container['webdav_username'];
    }

    /**
     * Sets webdav_username
     * @param string $webdav_username
     * @return $this
     */
    public function setWebdavUsername($webdav_username)
    {
        $this->container['webdav_username'] = $webdav_username;

        return $this;
    }

    /**
     * Gets webdav_password
     * @return string
     */
    public function getWebdavPassword()
    {
        return $this->container['webdav_password'];
    }

    /**
     * Sets webdav_password
     * @param string $webdav_password
     * @return $this
     */
    public function setWebdavPassword($webdav_password)
    {
        $this->container['webdav_password'] = $webdav_password;

        return $this;
    }

    /**
     * Gets webdav_url
     * @return string
     */
    public function getWebdavUrl()
    {
        return $this->container['webdav_url'];
    }

    /**
     * Sets webdav_url
     * @param string $webdav_url
     * @return $this
     */
    public function setWebdavUrl($webdav_url)
    {
        $this->container['webdav_url'] = $webdav_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Inwendo\WebDav\Common\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Inwendo\WebDav\Common\ObjectSerializer::sanitizeForSerialization($this));
    }
}


