<?php
/**
 * ContactApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Inwendo\WebDav\Common
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Inwendo WebDav Service
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Inwendo\WebDav\Common;

use \Inwendo\WebDav\Common\Configuration;
use \Inwendo\WebDav\Common\ApiClient;
use \Inwendo\WebDav\Common\ApiException;
use \Inwendo\WebDav\Common\ObjectSerializer;

/**
 * ContactApiTest Class Doc Comment
 *
 * @category Class
 * @package  Inwendo\WebDav\Common
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for deleteContactItem
     *
     * Removes the Contact resource..
     *
     */
    public function testDeleteContactItem()
    {

    }

    /**
     * Test case for getContactCollection
     *
     * Retrieves the collection of Contact resources..
     *
     */
    public function testGetContactCollection()
    {

    }

    /**
     * Test case for getContactItem
     *
     * Retrieves a Contact resource..
     *
     */
    public function testGetContactItem()
    {

    }

    /**
     * Test case for postContactCollection
     *
     * Creates a Contact resource..
     *
     */
    public function testPostContactCollection()
    {

    }

    /**
     * Test case for putContactItem
     *
     * Replaces the Contact resource..
     *
     */
    public function testPutContactItem()
    {

    }

}
